server:
  port: 3333
spring:
  boot:
    admin:
      client:
        url:
        - http://host.docker.internal:1111/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable dynamic routing with Eureka
          lower-case-service-id: true 
      routes:
        - id: consumer-service
          uri: http://host.docker.internal:3333
          predicates:
            - Path=/consumer-service/**
        # Treat service IDs as lowercase

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true

