server:
  port: 3333

eureka:
  instance:
    prefer-ip-address: true  # Ensures the IP address is used to register with Eureka
    ip-address: ${DOCKER_IP}  # You can pass this environment variable during Docker run to specify the IP
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/  # Using host.docker.internal for Eureka in Docker

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true

spring:
  boot:
    admin:
      client:
        url:
          - http://host.docker.internal:1111/  # Admin service URL pointing to host.docker.internal

logging:
  level:
    com.netflix.discovery: DEBUG  # Enables debug logging for Eureka discovery to troubleshoot issues
    org.springframework.cloud.netflix: DEBUG

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable dynamic routing with Eureka
          lower-case-service-id: true
      routes:
        - id: consumer-service
          uri: http://host.docker.internal:3333
          predicates:
            - Path=/consumer-service/**
        # Treat service IDs as lowercase
